#!/bin/bash
# Quick API test script for Categories & Questions endpoints

BASE_URL="http://localhost:3000"

echo "=== Categories & Questions API Test ==="
echo ""
echo "Available endpoints:"
echo ""
echo "Categories:"
echo "  GET    $BASE_URL/api/categories?typeId={id}"
echo "  POST   $BASE_URL/api/categories"
echo "  GET    $BASE_URL/api/categories/{id}"
echo "  PUT    $BASE_URL/api/categories/{id}"
echo "  DELETE $BASE_URL/api/categories/{id}"
echo "  PUT    $BASE_URL/api/categories/reorder"
echo ""
echo "Questions:"
echo "  GET    $BASE_URL/api/questions?categoryId={id}"
echo "  POST   $BASE_URL/api/questions"
echo "  GET    $BASE_URL/api/questions/{id}"
echo "  PUT    $BASE_URL/api/questions/{id}"
echo "  DELETE $BASE_URL/api/questions/{id}"
echo "  PUT    $BASE_URL/api/questions/reorder"
echo ""
echo "To test, start the dev server:"
echo "  npm run dev"
echo ""
echo "Then use curl or your API client to test endpoints."
